sudo: required
services:
  - docker

before_install:
  - docker build -t kabulski/frontend -f Dockerfile.dev .

script:
  - docker run kabulski/frontend npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react-frontend"
  env: "Dockerreactfrontend-env-1"
  bucket_name: "elasticbeanstalk-eu-west-1-116804838700"
  bucket_path: "docker-react-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY